### ISSUE TITLE
DOESN'T WORK IN SAFARI!?!?!

### ISSUE THREAD

**Issue by asolove** [gutentags/colorim.html#1]
PLEASE FIX IMMEDIATELY we use this in production and it is very unprofessional of you to offer a library without full browser support.

Reproduce the problem by opening [our home page](http://www.theworldsworstwebsiteever.com/).

**Comment by kriskowal** [comment]
:trollface:

**Comment by kriskowal** [comment]
So, I changed my mind about this repository and I intend to delete it. I certainly hope that the web archive caught this moment for posterity.

**Comment by kriskowal** [comment]
Fixed by cb0d1516223f336ce55a519e68152aad7afc904e
